print("======STUDENT DETAILS======")
name=str(input("Enter your name:"))
age=int(input("Enter your age:"))
roll_no=int(input("Enter your roll no:")) 
print("=====STUDENT DETAILS===")
print("Name is:",name)
print("Age is:",age)
print("Roll NO is:",roll_no) 